// Generated by CoffeeScript 1.3.3
(function() {
  var Contractor, Lawyer, logr, useful,
    __slice = [].slice;

  useful = require('useful');

  logr = require('node-logr').getLogger("Contractor");

  exports.Contractor = Contractor = (function() {

    function Contractor() {}

    Contractor.Required = function(description) {
      return useful.makeObject({
        paramType: "required",
        description: description
      });
    };

    Contractor.Optional = function(description) {
      return useful.makeObject({
        paramType: "optional",
        description: description
      });
    };

    Contractor.Create = function() {
      var envelope, name, params;
      name = arguments[0], params = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      params = params || [];
      envelope = function() {
        var message, param, value, values, _i, _len;
        values = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        message = [name];
        for (_i = 0, _len = params.length; _i < _len; _i++) {
          param = params[_i];
          value = values.shift();
          switch (param.paramType) {
            case "required":
              if (value === void 0) {
                logr.error("Bad arguments for contract \"" + name + "\", missing param:\"" + param.paramType + "\"-\"" + param.description + "\" args:" + (JSON.stringify(arguments)));
                return [name];
              } else {
                message.push(value);
              }
              break;
            case "optional":
              message.push(value);
          }
        }
        return message;
      };
      envelope.toString = function() {
        return name;
      };
      return envelope;
    };

    return Contractor;

  })();

  exports.Lawyer = Lawyer = (function() {

    function Lawyer() {}

    Lawyer.Read = function(contract, client) {
      return client[contract.shift()].apply(client, contract);
    };

    return Lawyer;

  })();

}).call(this);
